// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi053MK2azc5GsKCfBgTtZvr_inZjTG_8',
    appId: '1:940824697310:android:f11e064f6d261a6062654f',
    messagingSenderId: '940824697310',
    projectId: 'tourism-app-2f7c0',
    storageBucket: 'tourism-app-2f7c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc6GkFugNmMtGzgk_cOdZHb_dAV0UztP0',
    appId: '1:940824697310:ios:3068fe2126ea636a62654f',
    messagingSenderId: '940824697310',
    projectId: 'tourism-app-2f7c0',
    storageBucket: 'tourism-app-2f7c0.firebasestorage.app',
    androidClientId: '940824697310-d40np738p0j6k85ke5it8p1n44dnbedi.apps.googleusercontent.com',
    iosClientId: '940824697310-4rtsmoo2aiaknf0ogklm3bacnsft7i3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.jeddahTourism',
  );

}